apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/manifests

patches:
  - path: patch-configmap.yaml
  - path: patch-route.yaml

labels:
  - pairs:
      owner: user5
      app: bootcamp-prod

nameSuffix: -prod-user-5

images:
  - name: quay.io/rabenschlag/bootcamp
    newName: quay.io/rabenschlag/bootcamp
    newTag: prod
      
