apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/manifests

patches:
  - path: patch-configmap.yaml
  - path: patch-route.yaml

labels:
  - pairs:
      owner: user1
      app: bootcamp-prod

nameSuffix: -prod-user-1

images:
  - name: quay.io/tasdemir/bootcamp-v2
    newName: quay.io/tasdemir/bootcamp-v2
    newTag: v1
      
